name: _doxygen_doc_gen.yml
on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Environment
        run: |
          sudo apt-get update
          sudo apt-get install -y doxygen graphviz

      - name: Generate Doxygen
        run: |
          doxygen Doxyfile
